GameGuru/Files/scriptbank/ChromaticAbberation.lua

Is my setup ok , can you try to merge :)

Test branch with a little change, just to see if my setup is ok.

---

GameGuru/Files/effectbank/reloaded/apbr_core.fx
GameGuru/Files/effectbank/reloaded/entity_core.fx
GameGuru/Files/effectbank/reloaded/settings.fx
GameGuru/Files/effectbank/reloaded/terrain_basic.fx

Please merge this branch , i cant merge with my current branch and current master , so cant get my c changes into this branch. I need to get a fresh branch from the master when this is merged :)

Pe bugs and changes

---

GameGuru Core/Dark Basic Public Shared/Dark Basic Pro SDK/DarkSDKMore/DarkLUA/DarkLUA.cpp
GameGuru/Files/scriptbank/global.lua

Creating this pull request on behalf of AmenMoses, and need the branch reviewing.  The change involves adding five new LUA commands and accompanying documentation in the global script file.  Can someone check to make sure the commands do as described, that the documentation lines are sufficient and that the change to GetPlayerDistance has not changed the return values from legacy behavior (i.e. I noticed the SQRT final distance calculation are not given the axis-specific multiplications as ABSolute values, so, for example, 5*5 = 25 but -5*5 would be -25, which would affect the final total distance during the addition phase of the math).

Amen moses001

---

GameGuru Core/Dark Basic Public Shared/Dark Basic Pro SDK/Shared/Error/CError.cpp
GameGuru Core/Dark Basic Public Shared/Dark Basic Pro SDK/Shared/Objects/ShadowMapping/cShadowMaps.cpp
GameGuru Core/Dark Basic Public Shared/Dark Basic Pro SDK/Shared/Sprites/CSpriteManagerC.cpp
GameGuru Core/GameGuru/Source/M-Entity.cpp
GameGuru Core/GameGuru/Source/M-GridEdit.cpp

Fix for:
https://github.com/TheGameCreators/GameGuruRepo/issues/50
https://github.com/TheGameCreators/GameGuruRepo/issues/22
https://github.com/TheGameCreators/GameGuruRepo/issues/21
https://github.com/TheGameCreators/GameGuruRepo/issues/37

Pe bugfixes

---

GameGuru Core/Dark Basic Public Shared/Dark Basic Pro SDK/Shared/DBOFormat/DBOFormat.cpp
GameGuru Core/Dark Basic Public Shared/Dark Basic Pro SDK/Shared/Objects/CObjectsC.cpp
GameGuru Core/GameGuru/Source/G-Entity.cpp
GameGuru Core/GameGuru/Source/M-Entity.cpp
GameGuru Core/GameGuru/Source/M-Game.cpp
GameGuru Core/GameGuru/Source/M-GridEdit.cpp
GameGuru Core/GameGuru/Source/M-HUD.cpp
GameGuru Core/GameGuru/Source/M-Importer.cpp
GameGuru Core/GameGuru/Source/M-Visuals.cpp
GameGuru/Files/effectbank/reloaded/apbr_core.fx
GameGuru/Files/effectbank/reloaded/entity_core.fx
GameGuru/Files/scriptbank/ai/module_combatshoot.lua

PE: Fix for - Objects can displays wrong, if dbo is generated outside importer.
Original skin weight is not used but generated, this can give animation problems.
Also make sure dbo have all FVF semantic names when using skipfvfconvert=1.
https://github.com/TheGameCreators/GameGuruRepo/issues/104
https://github.com/TheGameCreators/GameGuruRepo/issues/54
PE: fix for - Black weird textures. 
Tangent is not calculated correct in ComputeTangentBasisEx, perhaps because we cant use the fixtangent flag that ruin bones ? , this calculation have been moved.
Tangent calculation added to vertex shaders.
https://github.com/TheGameCreators/GameGuruRepo/issues/85
https://github.com/TheGameCreators/GameGuruRepo/issues/54
Some textures do not have _d,_color,_albedo , so always reset. …

Preben bugfix additions

---

GameGuru Core/Dark Basic Public Shared/Dark Basic Pro SDK/Shared/Objects/CObjectManagerC.cpp
GameGuru Core/GameGuru/Source/G-Entity.cpp
GameGuru Core/GameGuru/Source/M-Game.cpp
GameGuru Core/GameGuru/Source/M-Importer.cpp
GameGuru/Files/effectbank/reloaded/entity_water.fx
GameGuru/Files/effectbank/reloaded/settings.fx
GameGuru/Files/effectbank/reloaded/sky_core.fx
GameGuru/Files/effectbank/reloaded/sprite_basic.fx
GameGuru/Files/effectbank/reloaded/terrain_basic.fx

Everything including this , is now in 2018.03.21 Public Preview.

2018.03.21 Public Preview

---

GameGuru/Files/scriptbank/healingzone.lua

Healing Zone no longer exceeds maximum health.

healingzone.lua

---

GameGuru Core/GameGuru/Source/M-LUA-General.cpp
GameGuru Core/GameGuru/Source/M-MapFile.cpp

Fix Bug -  SetSkyTo() Command

---

GameGuru/Files/scriptbank/light2.lua

light with this script can switch on and off with a switch entity (switch settings: light name in if used field and switchmain.lua as main) default light setting is off

add second light script 

---

GameGuru Core/GameGuru/Include/gameguru.h
GameGuru Core/GameGuru/Source/Common.cpp
GameGuru Core/GameGuru/Source/M-Game.cpp
GameGuru/setup.ini

added a flag to reload gunspec data from guns (usefull for artists who not want to restart GG every time, they make a change to the gunspec)

reload gunspec data in testgame flag

---

GameGuru Core/GameGuru/Source/M-MapFile.cpp

Fixed the standalone export for multitextured models with .png textures

Add support for .png textures in multitextured models

---

GameGuru Core/GameGuru/Source/M-Entity.cpp

comment modification

---

GameGuru Core/GameGuru/Source/M-EBE.cpp
GameGuru Core/GameGuru/Source/M-LUA-Entity.cpp
GameGuru Core/GameGuru/Source/M-LUA.cpp
GameGuru/Files/effectbank/reloaded/apbr_core.fx

Fix Bug #110

---

GameGuru/Files/scriptbank/gameplayercontrol.lua

Fix third person clipping through walls ( Fix #413 and Fix #523 )

12_06_2019 Fix third person clipping

---

GameGuru Core/Dark Basic Public Shared/Dark Basic Pro SDK/Shared/Image/CImageC.cpp
GameGuru Core/Dark Basic Public Shared/Dark Basic Pro SDK/Shared/Objects/CObjectManagerC.cpp
GameGuru Core/GameGuru/Include/Common.h
GameGuru Core/GameGuru/Include/M-LUA-Entity.h
GameGuru Core/GameGuru/Include/Types.h
GameGuru Core/GameGuru/Include/gameguru.h
GameGuru Core/GameGuru/Source/Common.cpp
GameGuru Core/GameGuru/Source/G-Entity.cpp
GameGuru Core/GameGuru/Source/G-Gun.cpp
GameGuru Core/GameGuru/Source/G-Lighting.cpp
GameGuru Core/GameGuru/Source/M-Entity.cpp
GameGuru Core/GameGuru/Source/M-Game.cpp
GameGuru Core/GameGuru/Source/M-GridEdit.cpp
GameGuru Core/GameGuru/Source/M-LUA-Entity.cpp
GameGuru Core/GameGuru/Source/M-LUA.cpp
GameGuru Core/GameGuru/Source/M-Lightmapping.cpp
GameGuru Core/GameGuru/Source/M-MapFile.cpp
GameGuru Core/GameGuru/Source/M-Particles.cpp
GameGuru Core/GameGuru/Source/M-Postprocess.cpp
GameGuru Core/GameGuru/Source/M-Terrain.cpp
GameGuru Core/GameGuru/Source/M-Visuals.cpp
GameGuru/Files/effectbank/reloaded/apbr_core.fx
GameGuru/Files/effectbank/reloaded/apbr_lightmapped_illum.fx
GameGuru/Files/scriptbank/global.lua

@LeeBamberTGC
Please so not close any issues referred here , they need confirmation.
( if updating beta , please remember to compile ALL shaders , needed for this to work ).
-- changes --
Lightmapper - Added illumination/emissive support to lightmapper.
fix issue: https://github.com/TheGameCreators/GameGuruRepo/issues/345
Particle - Fixed bug that can cause any random object in level to get particle shader effect. ( z depth , transparent problems ).
fix issue: https://github.com/TheGameCreators/GameGuruRepo/issues/548
fix issue: https://forum.game-guru.com/thread/220798?page=2#msg2616640
Bug - Gun smoke setup , was changing effect on wrong object.
Water Bug , some transparet objects did not display below water line.
fix issue: https://github.com/TheGameCreators/GameGuruRepo/issues/473 …

PE June Update 4

---

GameGuru Core/Dark Basic Public Shared/Dark Basic Pro SDK/DarkSDKMore/BlitzTerrain/main.cpp
GameGuru Core/Dark Basic Public Shared/Dark Basic Pro SDK/Shared/Objects/CObjectManagerC.cpp
GameGuru Core/GameGuru/Source/M-Game.cpp
GameGuru/Files/effectbank/reloaded/apbr_core.fx

Require ALL shaders to be recompiled :)

Beta performance fixes

---

GameGuru Core/GameGuru/Source/M-Game.cpp

a object did not get the correct effect , fixed.

PE: Fix - a object did not get the correct effect, this fixed it.

---

GameGuru Core/Dark Basic Public Shared/Dark Basic Pro SDK/DarkSDKMore/DarkLUA/DarkLUA.cpp
GameGuru Core/GameGuru/Source/G-Entity.cpp
GameGuru Core/GameGuru/Source/M-DAI.cpp
GameGuru Core/GameGuru/Source/M-Game.cpp
GameGuru Core/GameGuru/Source/M-LUA-Entity.cpp
GameGuru Core/GameGuru/Source/M-LUA-General.cpp
GameGuru Core/GameGuru/Source/M-MP.cpp
GameGuru Core/GameGuru/Source/M-Physics.cpp
GameGuru Core/GameGuru/Source/M-Terrain.cpp
GameGuru Core/GameGuru/Source/M-Weapon.cpp
GameGuru/setup.ini

Fix for bugs reported by PP testing.

PP fixer 2019 23 09

---

GameGuru Core/GameGuru/Imgui/imgui_gg_dx11.cpp
GameGuru Core/GameGuru/Imgui/imgui_gg_dx11.h
GameGuru Core/GameGuru/Source/M-GridEdit.cpp

This one should be set to merge into ProjectV3 , but please check :)

ProjectV3 additions

---

GameGuru Core/GameGuru/Include/M-MapFile.h
GameGuru Core/GameGuru/Include/Types.h
GameGuru Core/GameGuru/Include/cStr.h
GameGuru Core/GameGuru/Source/Common-Images.cpp
GameGuru Core/GameGuru/Source/G-Entity.cpp
GameGuru Core/GameGuru/Source/M-Game.cpp
GameGuru Core/GameGuru/Source/M-LUA-Entity.cpp
GameGuru Core/GameGuru/Source/M-LUA-General.cpp
GameGuru Core/GameGuru/Source/M-MapFile.cpp
GameGuru Core/GameGuru/Source/M-Physics.cpp
GameGuru Core/GameGuru/Source/M-Sliders.cpp
GameGuru Core/GameGuru/Source/M-Terrain.cpp
GameGuru Core/GameGuru/Source/M-Weapon.cpp
GameGuru Core/GameGuru/Source/cStr.cpp
GameGuru/Files/effectbank/reloaded/apbr_core.fx
GameGuru/Files/effectbank/reloaded/settings.fx
GameGuru/ggprecompile.lua

@Lee just keep this open until you decide to make a new GG release.
I will add to this branch, if anything else show up.
problems:
https://github.com/TheGameCreators/GameGuruRepo/issues/635

PE: Fix for GG Version 2019.10.04

---

GameGuru/Files/scriptbank/gameplayercontrol.lua

Fix #639 and fix #168 (Thirdperson moon walk)

---

GameGuru Core/GameGuru/Entity FPE Fixes/entitybank/Bridges/tunnel.fpe
GameGuru Core/GameGuru/Entity FPE Fixes/entitybank/Buildings/Tent (Canvas Pavilion).fpe
GameGuru Core/GameGuru/Entity FPE Fixes/entitybank/Buildings/Tent (Netting Pavilion).fpe
GameGuru Core/GameGuru/Entity FPE Fixes/entitybank/Fantasy Pack/Buildings/Aztec Shine 1.fpe
GameGuru Core/GameGuru/Entity FPE Fixes/entitybank/Fantasy Pack/Buildings/Aztec Shrine 2.fpe
GameGuru Core/GameGuru/Entity FPE Fixes/entitybank/Fantasy Pack/Buildings/Aztec Shrine 3.fpe
GameGuru Core/GameGuru/Entity FPE Fixes/entitybank/Mega Pack 02/Buildings/Entrance.fpe
GameGuru Core/GameGuru/Entity FPE Fixes/entitybank/Mega Pack 02/Buildings/Portcullis.fpe

A series of fixes to various assets that were preventing the player and AI from entering structures.
This fixes some age old issues:
https://steamcommunity.com/app/266310/discussions/1/523890046875316384/

Various Asset Collision Fixes

---

GameGuru Core/GameGuru/Entity FPE Fixes/content/Files/entitybank/Scenery/Propane Tank.fpe

Small change to make propane tank explosive if shot.

Makes Propane Tank Explosive

---

GameGuru Core/GameGuru/Source/M-Titles.cpp

PE: Request from GraPhiX , not to display terrain when in "game menu" and terrain is hidden.

PE: Request from GraPhiX.

---

GameGuru Core/GameGuru/Shaders and Scripts/scriptbank/global.lua

minor typo fixes where "get" should be "set"

GGC - Update global.lua (minor typo fixes)
