Dark-Basic-Software-Limited/GameGuruRepo

GameGuru Core/GameGuru/Source/M-Entity.cpp
GameGuru Core/GameGuru/Source/M-GridEdit.cpp
GameGuru/Files/effectbank/reloaded/decal_animate4.fx
GameGuru/Files/effectbank/reloaded/decal_animate8.fx
GameGuru/Files/effectbank/reloaded/decal_basic.fx
GameGuru/Files/effectbank/reloaded/settings.fx

fix:
https://github.com/TheGameCreators/GameGuruRepo/issues/69
https://github.com/TheGameCreators/GameGuruRepo/issues/53
Added: blending on particle/explosion/decals for better effects.
Removed: alpha clip on particle/explosion/decals , and moved it as a setting #define ENABLEDECALALPHACLIP (disabled by default).
The DX11 blending is way better and should open up for some great effects.
Added: PBR overwrite support for old multi textured models with no texture in fpe.

Pe pp2 bugs changes

---

GameGuru Core/GameGuru/Include/Types.h
GameGuru Core/GameGuru/Source/M-Entity.cpp

appendanimmax dont have a default in : entityprofiletype
In my case where it was hanging: appendanimmax=573444874 value_s=road_straight01.x
Happen if you are unlucky and get mem area where "appendanimmax" are not already set to zero in.
entity_loaddata() -> for ( int aa = 1 ; aa <= t.entityprofile[t.entid].appendanimmax; aa++ )

PE BUG FIX: GG sometimes hang.

---

GameGuru Core/GameGuru/Source/M-Physics.cpp

PE: Fix - physics system is fixed at 60 FPS, if you have a lower or higher FPS the physics system do not work, and produce wrong player movement and physics behavior.

PE: Fix - physics system is fixed at 60 FPS

---

GameGuru Core/Dark Basic Public Shared/Dark Basic Pro SDK/DarkSDKMore/BlitzTerrain/main.h
GameGuru Core/Dark Basic Public Shared/Dark Basic Pro SDK/DarkSDKMore/DarkLUA/DarkLUA.cpp
GameGuru Core/Dark Basic Public Shared/Dark Basic Pro SDK/Shared/Animation/CAnimation.cpp
GameGuru Core/Dark Basic Public Shared/Dark Basic Pro SDK/Shared/Objects/BoxCollision/CCollision.cpp
GameGuru Core/GameGuru/Include/gameguru.h
GameGuru Core/GameGuru/Source/Common-Images.cpp
GameGuru Core/GameGuru/Source/Common.cpp
GameGuru Core/GameGuru/Source/G-Entity.cpp
GameGuru Core/GameGuru/Source/M-Debug.cpp
GameGuru Core/GameGuru/Source/M-Entity.cpp
GameGuru Core/GameGuru/Source/M-MapFile.cpp
GameGuru Core/Include/CAnimation.h
GameGuru IDE/MainFrm.cpp
GameGuru/Files/effectbank/reloaded/apbr_basic.fx
GameGuru/Files/effectbank/reloaded/apbr_core.fx
GameGuru/Files/effectbank/reloaded/apbr_illum.fx
GameGuru/setup.ini

Im on a old branch , and need a merge so i can get all the latest installed locally :)
This include some OLD and new fixes:
PE: setup.ini - This will enable delayed Video loading, and will not use any memory before a video is actually playing, and when video is done all memory is released.
So if you use Video in your level this will save you around 90mb memory for each video you have on your level. ( no matter if they are used or not ).
videoprecacheframes=1
videodelayedload=1
PE: setup.ini - For games that dont use AI, setting these to 1 will give you faster loading and save you around 300mb on a avg. level.
aidisabletreeobstacles=0
aidisableobstacles=0
Should not be used for now, but will be expanded as we move forward:
skipunusedtextures=0
PE: Shaders - allow artist to make glass not …

PE: 11-06-2019

---

GameGuru Core/Dark Basic Public Shared/Dark Basic Pro SDK/DarkSDKMore/DarkLUA/DarkLUA.cpp
GameGuru Core/Dark Basic Public Shared/Dark Basic Pro SDK/DarkSDKMore/SimonReloaded/SimonReloaded.cpp
GameGuru Core/Dark Basic Public Shared/Dark Basic Pro SDK/Shared/Bullet/BulletPhysics.CPP
GameGuru Core/Dark Basic Public Shared/Dark Basic Pro SDK/Shared/DBOFormat/DBOData.h
GameGuru Core/Dark Basic Public Shared/Dark Basic Pro SDK/Shared/Objects/CObjectManagerC.cpp
GameGuru Core/Dark Basic Public Shared/Dark Basic Pro SDK/Shared/Objects/CObjectsC.cpp
GameGuru Core/Dark Basic Public Shared/Dark Basic Pro SDK/Shared/Objects/CommonC.cpp
GameGuru Core/GameGuru/Include/gameguru.h
GameGuru Core/GameGuru/Source/Common.cpp
GameGuru Core/GameGuru/Source/M-CharacterKit.cpp
GameGuru Core/GameGuru/Source/M-MapFile.cpp
GameGuru Core/GameGuru/Source/M-Terrain.cpp
GameGuru Core/GameGuru/Source/M-Visuals.cpp
GameGuru Core/Include/BulletPhysics.H
GameGuru Core/Include/SimonReloaded.h

Added: Vegetation below water is now possible without clipping problems.
SetObjectTransparency(Obj,8) mode, to trigger render before water.
Added: setup.ini , (default) usegrassbelowwater=1 allow render of grass grid above/below waterline at the same time.
Fix: Distance to water object (0,600,0)-campos , prevented decals/transparent objects below water from displaying.
Editor: Changed editor water to use SetObjectTransparency(Obj,5) , so it act like in test game.
Fix: slow down physics fall speed and lower gravity when hitting water.
https://github.com/TheGameCreators/GameGuruRepo/issues/565
fix: Character Creator you cant see full list after installing additional assets.
https://github.com/TheGameCreators/GameGuruRepo/issues/410#issuecomment-506831070

PE-JUNE-7 update.

---

GameGuru Core/GameGuru/Shaders and Scripts/scriptbank/winzone.lua

Updates Win Zones to allow for changing any Win Zone into an inactive state, that then requires activation from "ifused" fields in Trigger Zones or collectable entities.
This is a response to the feature request for #3618
Usage:
1. Place a winzone on the map
2. click on the win zone and change its name from "Win Zone" to a custom name
3. Place a trigger zone on the map
4. click on the trigger zone and put the custom name of the win zone in the ifused field of the trigger zone
This will make it so the player is required to reach the trigger zone before he can exit the level at the win zone.
This script update does not affect how Win Zones previously worked. If you keep them named "Win Zone" in the properties panel they will operate as normal. This also means that old projects will not be …

Improved winzone.lua - adds ability to lock Win Zones for Trigger Zone Activation

---

GameGuru Core/GameGuru/Shaders and Scripts/scriptbank/showhuds.lua

To compliment the hidehuds.lua script for Trigger Zones, showhuds.lua brings back huds that were made hidden.

New Script - showhuds.lua

---

GameGuru Core/GameGuru/Shaders and Scripts/scriptbank/gameplayercontrol.lua

Multiple Fixes and Changes to Player's Dying Effect trigger:
Fixes issue causing dying effect when the player was barely hurt:
Previously if the player was ever hurt, even by 1 point of damage, the player would act as if he was dying. The screen would go red and a heart-beat sound would play repeatedly until the player finds a health item or regenerates health. This used to occur instantly because the player's main script was set to cause this effect whenever the player's health was lower than 100. So for example if your health was 99, your game would assume the player is dying and cause a heart beat sound to play and flash the screen red. This change sets to check if player's health is less than 50% of its set maximum in the editor. Meaning less than 50/100 or less than 150/300 etc for …

Fixes for Dying Effects (Heartbeat + Red Screen) 

---

GameGuru Core/GameGuru/Shaders and Scripts/scriptbank/animation_finder.lua

Added animation finder to scriptbank and fixed the issue preventing Q and E from being received when Caps-Lock is one.  Fixes issue #4098 that I encountered today.

Animation Finder Added and Corrected

---

GameGuru Core/GameGuru/Entity FPE Fixes/content/Files/entitybank/Model Pack 02/Decals/Light/Lightrays.fpe

This fixes the issue with the lightray decal which is intended to be a light ray coming out from a window with no rotation. 
Unlike other decals, this decal when it rotates to always face the player, breaks the illusion that its emitting from a fixed position. By removing the decal facing lua in the FPE, this fixes the light-ray's casting direction.
Essentially it now operates as it did in FPSC, which is to add atmosphere to areas with windows.

Fixed Rotation Issue with Lightray Decal

---

GameGuru Core/GameGuru/Shaders and Scripts/scriptbank/gameplayercontrol.lua

This is fixes a new bug that was causing the red death fog to fall out of proportion to health, causing the screen to sometimes go blue.
line 1808 in gameplayercontrol.lua:
Previous:
ttTargetRed = 0.5 - (g_PlayerHealth/200.0)
Now:
ttTargetRed = 0.5 - (g_PlayerHealth/g_gameloop_StartHealth / 200.0)

Quick Fix for Blue Death Fog Bug

---

GameGuru Core/GameGuru/Shaders and Scripts/scriptbank/health.lua

This GGC health.lua update will prevent health from exceeding the maximum player health set within the Player Start Marker, when collecting items such as medkits which should operate as health recovery items and healing items, rather than boosters.
This update also will prompt a message if the players health is already full.
(not sure if its possible to ignore the first commit and only accept the latest. As there is a mistake in the first commit and i'm unsure how to remove it. However the latest should override it.)

GGC - Health.lua Update

---

GameGuru Core/GameGuru/Shaders and Scripts/scriptbank/proximine.lua

This update will make it so the countdown timer sound effect doesn't ever play twice over. Which fixes a bug whereas the count down timer can sometimes be heard even after having exploded.
Additionally this update allows for the option of "IfUsed" on switches to detonate specified proximity mines on the map.

GGC - Proximity Mine Sound Issue Fix + IfUsed Feature Added

---

GameGuru Core/GameGuru/Shaders and Scripts/scriptbank/jetpackfuel.lua

This script when applied to an entity will turn the entity into a collectable item that will increase/re-fill the player's Jet Pack Fuel.
(I do have an entity associated with this I'd also like to include but am unsure of how to upload its FPE and BMP files to the Github without pushing other unnecessary items along with it.)

GGC - Added Jet Pack Fuel Script

---

GameGuru Core/GameGuru/Shaders and Scripts/scriptbank/hurt.lua

This script for some reason had a comment of "Detonate proximity mine" although it is not associated with proximity mines.
The comment within the script has been removed in this update.

GGC - Update hurt.lua

---

GameGuru Core/GameGuru/Shaders and Scripts/scriptbank/ammo.lua
GameGuru Core/GameGuru/Shaders and Scripts/scriptbank/ammo_highlight.lua

This update will allow for 3rd person player characters to collect ammo for their current weapon.
3rd person player character currently in Game Guru Classic only allows for one weapon to be used, however previously this also meant that the collection of ammo was being blocked. This prevented the player from being able to replenish ammo for the current and only weapon he/she could carry. This has now been fixed here.

GGC - Fix/Feature Added - 3rd Person Player Ammo Collection

---

GameGuru Core/GameGuru/Shaders and Scripts/scriptbank/gameloop.lua

Fixes an issue of which would prevent the player from drowning if health regeneration was enabled. Better to have this as a baseline. Since it essentially voided the player's ability to drown.

GGC - Fixed Issue - Unable to Drown if Health Regen Enabled

---

GameGuru Core/GameGuru/Shaders and Scripts/scriptbank/global.lua

A new Lua command has been created called: MoveDown(e,v)
This is to compliment the existing commands MoveUp(e,v), MoveForward(e,v) and MoveBackward(e,v)
(Commonly users just getting into GGC with Lua ask why MoveDown does not work. This is because it does not exist.)

GGC - New Lua Command - MoveDown(e,v)

---

GameGuru Core/GameGuru/Shaders and Scripts/scriptbank/global.lua

GetFileExists(filename) added to global.lua allows you to check if a file of any kind exists. 
This is also good for preventing GGC crashes for when attempting to load images/sprites, audio and video as users can use it to check if a file exists before attempting to load them. It has a wide range of possibilities.  It can also be used to check if certain Lua scripts exists or any other file type. It scans from within "files" root.
Example:
if GetFileExists("scriptbank/example.lua") == 1 then
Prompt("File exists!")
else
Prompt("File does not exist!")
end

GGC - New Lua Command - GetFileExists(filename)

---

GameGuru Core/GameGuru/Files/entitybank/Collectables/Syringe.fpe

The Syringe Item will now make use of the new healthboost.lua script health boost (which was added some versions ago) which will increase the players health beyond that of the maximum.
Previously recovery, healing, health items would increase the health of the player exceeding the maximum health value. Which would go against recovery and healing methods and instead act as a boost or buff. We had since removed that and made them as healing items. Due to that, we dont have any items that act as boosts or buffs, so I've included the healthboost script to the syringe so it can operate as a health boost (and actually operate as original health did in early versions of GGC).

GGC - Modified Syringe.fpe to use healthboost.lua

---

GameGuru Core/GameGuru/Shaders and Scripts/scriptbank/key.lua

Collecting keys will now display the name of the key entity, thus allowing users to name their keys. For Example "Collected key" can now be "Collected Card 1" or "Collected Iron Key" etc. Whatever you name the key in the entity properties will be displayed when attempting to pick up a key and when the key has been collected.
Additionally, the key will automatically be collected in 3rd person if the player is within 80 units of the key, avoiding any issues people have raised related to collection distance and perspective issues with unique 3rd person player character models.

GGC - Improved Collectable Keys

---

GameGuru Core/GameGuru/Shaders and Scripts/scriptbank/gameplayercontrol.lua
GameGuru Core/GameGuru/Shaders and Scripts/scriptbank/global.lua

The playable map area is now dynamically customizable with this new command:
**PlayableArea( minx, maxx , minz ,maxz )**
-- Default Playable Map Size set in global.lua
g_mapsizeminx = 100
g_mapsizemaxx = 51100
g_mapsizeminz = 100
g_mapsizemaxz = 51100
This will allow for creating smaller playable areas (smaller levels) or even larger playable areas that go beyond the editable terrain  area (more ideal for space games).
If you know a bit of scripting you could technically even make the playable area change size dynamically based on different factors like completing quests or reaching different objects etc to be able to explore the wider map.
Another advantage of why you might want to change your playablearea to a smaller box, is say you have an island and you dont want the player to be …

GGC - New Lua Command - PlayableArea(minx,maxx,minz,maxz)

---

GameGuru Core/GameGuru/Shaders and Scripts/scriptbank/global.lua

Correction to GetEntityCollBox(e) reference in global.lua
The commands:
GetObjectCollBox
GetEntityCollBox
Were both incorrectly shown in the global.lua example leaving out the extra "L" character. This is why they didnt work.
Resolves this issue: #6111

GGC - Correction to GetEntityCollBox(e) reference in global.lua
